[build]
builder = "nixpacks"
buildCommand = ""

[variables]
NIXPACKS_PKGS = "wget wkhtmltopdf"

[deploy]
numReplicas = 1
startCommand = "DJANGO_SETTINGS_MODULE=cv_builder.settings daphne -b 0.0.0.0 -p $PORT cv_builder.asgi:application"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 