[build]
builder = "nixpacks"
buildCommand = ""

[variables]
NIXPACKS_PKGS = "wget libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info libcairo2 libgobject-2.0-0 libgirepository1.0-dev"

[deploy]
numReplicas = 1
startCommand = "DJANGO_SETTINGS_MODULE=cv_builder.settings daphne -b 0.0.0.0 -p $PORT cv_builder.asgi:application"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 