# Generated by Django 5.1.6 on 2025-02-07 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cvs", "XXXX_add_status_and_current_step"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cv",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.RemoveField(
            model_name="cv",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="cv",
            name="template",
        ),
        migrations.RemoveField(
            model_name="cv",
            name="title",
        ),
    ]
