# Generated by Django 5.1.6 on 2025-02-28 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Taslak"), ("completed", "Tamamlandı")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("current_step", models.IntegerField(default=0)),
                ("personal_info", models.JSONField(default=dict)),
                ("education", models.JSONField(default=list)),
                ("experience", models.JSONField(default=list)),
                ("skills", models.JSONField(default=list)),
                ("languages", models.JSONField(default=list)),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Video dosyası yükleyebilirsiniz",
                        null=True,
                        upload_to="cv_videos/",
                    ),
                ),
                ("video_description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CV",
                "verbose_name_plural": "CVs",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("issuer", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        help_text="PDF veya resim dosyası yükleyebilirsiniz",
                        null=True,
                        upload_to="certificates/",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        choices=[("pdf", "PDF"), ("image", "Image")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="cvs.cv",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CVTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(default="en", max_length=2)),
                ("personal_info", models.JSONField(default=dict)),
                ("education", models.JSONField(default=list)),
                ("experience", models.JSONField(default=list)),
                ("skills", models.JSONField(default=list)),
                ("languages", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="cvs.cv",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["cv", "language_code"],
                        name="cvs_cvtrans_cv_id_d5c906_idx",
                    )
                ],
                "unique_together": {("cv", "language_code")},
            },
        ),
    ]
