# Generated by Django 5.1.6 on 2025-02-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cvs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvtranslation",
            name="language_code",
            field=models.CharField(
                choices=[
                    ("tr", "Türkçe"),
                    ("en", "English"),
                    ("es", "Español"),
                    ("zh", "中文"),
                    ("ar", "العربية"),
                    ("hi", "हिन्दी"),
                ],
                default="en",
                max_length=2,
            ),
        ),
    ]
