# Generated by Django 5.1.6 on 2025-02-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cvs", "0001_alter_cv_options_remove_cv_is_public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="title",
            field=models.CharField(default="Untitled CV", max_length=100),
        ),
    ]
