# Generated by Django 5.1.6 on 2025-02-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cvs", "0002_cv_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cv",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "CV",
                "verbose_name_plural": "CVs",
            },
        ),
        migrations.AlterField(
            model_name="cv",
            name="education",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="cv",
            name="experience",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="cv",
            name="languages",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="cv",
            name="personal_info",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="cv",
            name="skills",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="cv",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
