# Generated by Django 5.1.6 on 2025-03-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cvs", "0002_alter_cvtranslation_language_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvtranslation",
            name="certificates",
            field=models.JSONField(default=list),
        ),
    ]
