# Generated by Django 5.1.6 on 2025-02-24 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cvs", "0003_alter_cv_options_alter_cv_education_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("issuer", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        help_text="PDF veya resim dosyası yükleyebilirsiniz",
                        null=True,
                        upload_to="certificates/",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        choices=[("pdf", "PDF"), ("image", "Image")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="cvs.cv",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
