# Generated by Django 5.1.6 on 2025-03-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cvs", "0003_cvtranslation_certificates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificate",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="description",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="issuer",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="name",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="url",
        ),
        migrations.AddField(
            model_name="certificate",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="translations",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="certificate",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="document_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
