# Generated by Django 5.1.6 on 2025-03-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cvs", "0005_delete_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name='cvtranslation',
            name='video_info',
            field=models.JSONField(default=dict),
        ),
    ]
