# Generated by Django 5.1.6 on 2025-03-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cvs", "0006_auto_20250302_0654"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="translation_key",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
