# Generated by Django 5.1.6 on 2025-03-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cvs", "0007_cv_translation_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="certificates",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="cv",
            name="video_info",
            field=models.JSONField(default=dict),
        ),
    ]
