# Generated by Django 5.1.6 on 2025-03-04 18:01

import cvs.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cvs", "0008_cv_certificates_cv_video_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Video dosyası yükleyebilirsiniz",
                null=True,
                upload_to="cv_videos/",
            ),
        ),
    ]
