# Generated by Django 5.1.6 on 2025-09-03 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "gateway_type",
                    models.CharField(
                        choices=[("paddle", "Paddle"), ("paytr", "PayTR Virtual POS")],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payment Gateway",
                "verbose_name_plural": "Payment Gateways",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("price_monthly", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_yearly", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("jobseeker", "Job Seeker"),
                            ("premium", "Premium"),
                        ],
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paddle_price_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paddle_product_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("features", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("canceled", "Canceled"),
                            ("expired", "Expired"),
                            ("trial", "Trial"),
                            ("pending", "Pending"),
                            ("past_due", "Past Due"),
                            ("paused", "Paused"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("trial_end_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                (
                    "payment_provider",
                    models.CharField(
                        choices=[("paddle", "Paddle"), ("paytr", "PayTR Virtual POS")],
                        default="paddle",
                        max_length=20,
                    ),
                ),
                ("next_payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "paddle_subscription_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paddle_customer_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paddle_plan_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paddle_update_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "paddle_cancel_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "paddle_checkout_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paddle_last_payment_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Subscription",
                "verbose_name_plural": "User Subscriptions",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPaymentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.CharField(blank=True, max_length=100, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_provider",
                    models.CharField(
                        choices=[("paddle", "Paddle"), ("paytr", "PayTR Virtual POS")],
                        default="paddle",
                        max_length=20,
                    ),
                ),
                (
                    "paddle_payment_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paddle_checkout_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paytr_merchant_oid",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paytr_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "paytr_payment_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("paytr_hash", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="subscriptions.usersubscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Payment History",
                "verbose_name_plural": "Subscription Payment Histories",
            },
        ),
    ]
