# Generated by Django 5.1.6 on 2025-04-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_paymentgateway_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpaymenthistory",
            name="payment_provider",
            field=models.CharField(
                choices=[("paddle", "Paddle"), ("paytr", "PayTR Virtual POS")],
                default="paddle",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpaymenthistory",
            name="paytr_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpaymenthistory",
            name="paytr_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionpaymenthistory",
            name="paytr_merchant_oid",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionpaymenthistory",
            name="paytr_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="cancel_at_period_end",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="next_payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="paddle_cancel_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="paddle_checkout_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="paddle_last_payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="paddle_plan_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="paddle_update_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="payment_provider",
            field=models.CharField(
                choices=[("paddle", "Paddle"), ("paytr", "PayTR Virtual POS")],
                default="paddle",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("canceled", "Canceled"),
                    ("expired", "Expired"),
                    ("trial", "Trial"),
                    ("pending", "Pending"),
                    ("past_due", "Past Due"),
                    ("paused", "Paused"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
