# Generated by Django 5.1.6 on 2025-09-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="The unique identifier for a post. Generated automatically from the title of the first translation.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
