# Generated by Django 5.1.6 on 2025-09-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_blogpost_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, help_text="The number of times the post has been viewed."
            ),
        ),
    ]
