# Generated by Django 5.1.6 on 2025-03-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_rename_is_used_passwordresettoken_used_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="paddle_customer_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Paddle Customer ID"
            ),
        ),
    ]
