# Generated by Django 5.1.6 on 2025-04-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_paddle_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Adres"),
        ),
    ]
